### ISSUE TITLE
Nuget references Scientist.Publishers.Shared, but nothing found

### ISSUE THREAD

**Issue by kimipsen** [nicostouch/scientist-dotnet-publishers#5]
When attempting to use the nuget package - Scientist.Publishers.Serilog - a dependency on Scientist.Publishers.Shared is required, but cannot be found on nuget.org.

**Comment by unleashed-jamest** [comment]
Ah sorry! That's my bad. I'll try to publish it at some stage today. Thanks for letting me know!

**Comment by james-s-tayler** [comment]
@kimipsen I've uploaded the missing nuget package and changed the reference from a project reference to a package reference in the serilog publisher.

It should be fixed by https://github.com/nicostouch/scientist-dotnet-publishers/pull/6

Sorry about that.
